# Generated by Django 5.0.1 on 2024-02-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='created_date',
        ),
    ]
