# Generated by Django 5.0.1 on 2024-02-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_business_seat_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='onboading_date',
            new_name='onboarding_date',
        ),
    ]
