# Generated by Django 5.0.1 on 2024-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_title_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='opening_quantity',
            field=models.FloatField(default=0),
        ),
    ]
