# Generated by Django 5.0.1 on 2024-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_item_grnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='special_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
