# Generated by Django 5.0.1 on 2024-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_grn_date_added_grn_special_note_grn_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='discount_flat_on_single_item',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='discount_flat_on_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='discount_free_items',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
