# Generated by Django 5.0.1 on 2024-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_grnitem_discount_flat_on_single_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='flat_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grn',
            name='percentage_discount',
            field=models.FloatField(default=0),
        ),
    ]
