# Generated by Django 5.0.1 on 2024-03-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_grn_flat_discount_grn_percentage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.grn'),
        ),
    ]
