# Generated by Django 5.0.1 on 2024-03-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_grn_is_finalized_grnitem_is_finalized_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnitem',
            old_name='price',
            new_name='item_price',
        ),
        migrations.RemoveField(
            model_name='grnitem',
            name='title',
        ),
    ]
