# Generated by Django 5.0.1 on 2024-03-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_grnitem_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnitem',
            name='item_price',
        ),
    ]
