# Generated by Django 5.0.1 on 2024-03-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_grnitem_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnitem',
            name='quantity',
        ),
    ]
