# Generated by Django 5.0.1 on 2024-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_grnitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grnitem',
            name='opening_quantity',
            field=models.FloatField(),
        ),
    ]
