# Generated by Django 5.0.1 on 2024-03-26 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_grnitem_price_alter_grnitem_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grnitem',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_grn_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
