# Generated by Django 5.0.1 on 2024-04-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_sr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sr',
            name='grn_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srs', to='inventory.grnitem'),
        ),
    ]
