# Generated by Django 5.0.1 on 2024-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_sr_grn_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sr',
            name='is_finalized',
        ),
        migrations.AddField(
            model_name='sr',
            name='item_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sr',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
