# Generated by Django 5.0.1 on 2024-04-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_sr_is_finalized_sr_item_cost_sr_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr',
            name='grn_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srs', to='inventory.grnitem'),
        ),
    ]
